const initialMockStateMovieDetails = {
  cardsData: {
    peopleList: [
      {
        id: 1,
        name: "Luke Skywalker",
        species: [1],
        birth_year: "19BBY",
        created: "2021-01-01",
        edited: "2021-01-02",
        eye_color: "blue",
        films: [1, 2],
        gender: "male",
        hair_color: "blond",
        height: "172",
        homeworld: 1,
        mass: "77",
        skin_color: "fair",
        starships: [1],
        url: "https://swapi.dev/api/people/1/",
        vehicles: [4, 6],
      },
      {
        id: 2,
        name: "Darth Vader",
        species: [1],
        birth_year: "41.9BBY",
        created: "2021-01-01",
        edited: "2021-01-02",
        eye_color: "yellow",
        films: [1, 2, 3],
        gender: "male",
        hair_color: "none",
        height: "202",
        homeworld: 1,
        mass: "136",
        skin_color: "white",
        starships: [2],
        url: "https://swapi.dev/api/people/4/",
        vehicles: [],
      },
    ],
    filmList: [
      {
        id: 1,
        title: "A New Hope",
        episode_id: 4,
        opening_crawl: "It is a period of civil war...",
        director: "George Lucas",
        producer: "Gary Kurtz, Rick McCallum",
        release_date: "1977-05-25",
        characters: [1, 2],
        planets: [1],
        starships: [1, 2],
        vehicles: [4, 6],
        created: "2021-01-01",
        edited: "2021-01-02",
        url: "https://swapi.dev/api/films/1/",
      },
      {
        id: 2,
        title: "The Empire Strikes Back",
        episode_id: 5,
        opening_crawl: "It is a dark time for the Rebellion...",
        director: "Irvin Kershner",
        producer: "Gary Kurtz, Rick McCallum",
        release_date: "1980-05-17",
        characters: [1, 2],
        planets: [2],
        starships: [1, 2],
        vehicles: [8],
        created: "2021-01-01",
        edited: "2021-01-02",
        url: "https://swapi.dev/api/films/2/",
      },
      {
        id: 3,
        title: "Return of the Jedi",
        episode_id: 6,
        opening_crawl: "Luke Skywalker has returned to his home planet...",
        director: "Richard Marquand",
        producer: "Howard G. Kazanjian, George Lucas, Rick McCallum",
        release_date: "1983-05-25",
        characters: [1, 2],
        planets: [3],
        starships: [1, 3],
        vehicles: [8, 10],
        created: "2021-01-01",
        edited: "2021-01-02",
        url: "https://swapi.dev/api/films/3/",
      },
    ],
    starshipList: [
      {
        id: 1,
        name: "X-wing",
        model: "T-65 X-wing",
        manufacturer: "Incom Corporation",
        MGLT: "100",
        cargo_capacity: 110,
        consumables: "1 week",
        cost_in_credits: 149999,
        created: "2021-01-01",
        crew: 1,
        edited: "2021-01-02",
        hyperdrive_rating: 1.0,
        length: 12.5,
        max_atmosphering_speed: "1050",
        passengers: 0,
        starship_class: "Starfighter",
        films: [1, 2, 3],
        pilots: [1],
        url: "https://swapi.dev/api/starships/1/",
      },
      {
        id: 2,
        name: "TIE Advanced x1",
        model: "Twin Ion Engine Advanced x1",
        manufacturer: "Sienar Fleet Systems",
        MGLT: "100",
        cargo_capacity: 150,
        consumables: "5 days",
        cost_in_credits: 250000,
        created: "2021-01-01",
        crew: 1,
        edited: "2021-01-02",
        hyperdrive_rating: 1.0,
        length: 9.2,
        max_atmosphering_speed: "1200",
        passengers: 0,
        starship_class: "Starfighter",
        films: [1, 2],
        pilots: [2],
        url: "https://swapi.dev/api/starships/2/",
      },
    ],
  },
};
const initialMockStateCards = {
  cardsData: {
    peopleList: [
      {
        id: 1,
        name: "Luke Skywalker",
        species: [1],
        birth_year: "19BBY",
        created: "2021-01-01",
        edited: "2021-01-02",
        eye_color: "blue",
        films: [1, 2],
        gender: "male",
        hair_color: "blond",
        height: "172",
        homeworld: 1,
        mass: "77",
        skin_color: "fair",
        starships: [1],
        url: "https://swapi.dev/api/people/1/",
        vehicles: [4, 6],
      },
      {
        id: 2,
        name: "Darth Vader",
        species: [1],
        birth_year: "41.9BBY",
        created: "2021-01-01",
        edited: "2021-01-02",
        eye_color: "yellow",
        films: [1, 2, 3],
        gender: "male",
        hair_color: "none",
        height: "202",
        homeworld: 1,
        mass: "136",
        skin_color: "white",
        starships: [2],
        url: "https://swapi.dev/api/people/4/",
        vehicles: [],
      },
    ],
  },
};
const initialMockStateHome = {
  cardsData: {
    peopleList: [],
    currentPage: 1,
    filmList: [],
    starshipList: [],
  },
};
const initialMockStatePagination = {
  cardsData: {
    currentPage: 1,
  },
};
export {
  initialMockStateMovieDetails,
  initialMockStateCards,
  initialMockStateHome,
  initialMockStatePagination,
};
